### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by wuhao21**
Remove extra s

### CODE REVIEW

**Comment by lixin-wei** [comment]
Oh, never imagined this project will be seen by someone. Thanks, bro :)

**Comment by lixin-wei** [comment]
Besides, I found some parts of the README is stale. Updated, please pull and check again.

Also removed the DingTalk notification dependency, it's not commonly used. Email notification is enough, I think.

**Comment by wuhao21** [comment]
> Oh, nevery imagined this project will be seen by someone. Thanks bro :)

It's really helpful! I added a discord notification feature in my fork and it's already running for 12 hours.

**Comment by lixin-wei** [comment]
Nice work! And good luck for your visa! I'm happy that it helped you.

I'm thinking about making the notification plugable. E.g. Select which you want in the configuration file. So you can contribute you code back. Welcome for PRs if you are interested to help :)

**Pull request merged**
